Set hamburger button 'position' attribute to 'fixed' & adjusted posit…
codesydney/codesydney pull request #91
Opened 2020-10-11 03:25 UTC by QjStout

…ioning.

## Rationale

Accessing the navigation menu required scrolling to the top of the page.
Fixing the hamburger button to the viewport means it will stay accessible as the user scrolls.

## Advice for Reviewers & Testing Notes

- Scroll down the page.
- Hamburger button should stay fixed to the top left of the browser.

## Task Name

- closes #69

2020-10-12 10:09 UTC, engramar approved these changes
All good @QjStout. Thanks. 

![issue69](https://user-images.githubusercontent.com/7553347/95734478-3ca2d500-0ccf-11eb-8a9a-9f74e4b1379c.gif)

2020-10-12 11:07 UTC, chenhe-henry requested changes
Looks good on the homepage and friends page, but when switch to the contact page, cannot see the hamburger button.

![image](https://user-images.githubusercontent.com/53432888/95739773-15e89c80-0cd7-11eb-9942-7080ba99d8d4.png)

Please check that. Thanks @QjStout

2020-10-12 11:38 UTC, QjStout commented
Huh, didn't notice that. Good spotting. I'll take a look soon.

2020-10-12 20:02 UTC, engramar commented
Looks like I did not wear my testing hat properly on this one. =) Good one, @chenhe-henry

2020-10-13 08:47 UTC, QjStout commented
Was a bit confused there, but I eventually figured out that the hamburger was hidden behind the contact page.
This will be solved by issue #87 when it's implemented. For now, I just added a blank div to make some space so we can see the hamburger. This div will need to be removed after #87 is implemented.

2020-10-14 02:16 UTC, merged